### ISSUE TITLE
Some change requests

### ISSUE THREAD

**Issue by firatatalay** [melikeg/javascript-password-generator#1]
Dear @melikeg , 

The app has been a simple and very useful app and Im using the app actively in my working life.
I want to give a few feedback.

- I think that there should not be Turkish characters in the passwords generated. For example, the lowercase letter "ı". It should be "i".
- Those who use password applications usually use 16 characters and numbers included. Therefore, the **Numbers field should also be selected** as default and the **character length can be 16**.
- When the application is first opened, instead of having the Password field empty, it can be opened directly by generating a password.

Best regards.

**Comment by melikeg** [comment]
Dear @firatatalay,

Thank you for your valuable feedback. I accidently overlooked the Turkish characters in password creation. I will change the other two issues according to your advice. Thank you for your interest in my application.

Best regards.

**Comment by melikeg** [comment]
added this: 2301ffaa197e636a70f4e76c62123e7dae056760
